### ISSUE TITLE
Syntax error: unexpected '*'

### ISSUE THREAD

**Issue by rawtalent06** [mjdorma/yara-ctypes#4]
When using the latest update, I am receiving the following error message:

Failed to load rules with the following error(s):
syntax error, unexpected '*', expecting _CONDITION_
unterminated string

You could blacklist the erroneous rules using:
 --blacklist=

This message does not appear when using the the revision before the latest update.  I have narrowed down the issue that is causing this in my .yar file.  If you put comments inside the rule and have one of your strings have comment delimiters, the code is looking for the opening and closing comment delimiters.  Below is my example rule file that is causing the issue:

rule testRule1
{
    meta:
        author="Test"
        comment="Test 2"
/*
    Some comments
_/
    strings:
        $str79="Accept: */_"

```
condition:
    all of them
```

}

**Comment by mjdorma** [comment]
libyara.so from 1.7.0 has now been reverted to its previous edition.

There is a test in test_rules.py that will hopefully catch this particular issue again in the future.  

As a future TODO effort, fleshing out test_rules.py with more valid yara rule permutations is a great way to ensure yara-ctypes doesn't ship with a faulty build of libyara.so into the future...
