### ISSUE TITLE
distribute versions

### ISSUE THREAD

**Issue by mrtizmo** [mjdorma/yara-ctypes#6]
When I install the yara package into a virtualenv on my Ubuntu 12.04 system, it complains that the distribute version is too old (it is 0.6.24 and yara wants >=0.6.25).

This is what happens when I try to install yara without first upgrading distribute

```
$ pip install yara
Downloading/unpacking yara
  Downloading yara-1.7.5.tar.gz (392Kb): 392Kb downloaded
  Running setup.py egg_info for package yara
    The required version of distribute (>=0.6.25) is not available,
    and can't be installed while this script is running. Please
    install a more recent version first, using
    'easy_install -U distribute'.

    (Currently using distribute 0.6.24 (/home/nick/msvirtualenv/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg))
    Complete output from command python setup.py egg_info:
    The required version of distribute (>=0.6.25) is not available,

and can't be installed while this script is running. Please

install a more recent version first, using

'easy_install -U distribute'.



(Currently using distribute 0.6.24 (/home/nick/msvirtualenv/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg))

----------------------------------------
Command python setup.py egg_info failed with error code 2 in /home/nick/msvirtualenv/build/yara
Storing complete log in /home/nick/.pip/pip.log
```

Ok, so, I have to upgrade distribute prior to installing the yara package.
pip install -U distribute

Then I can install the yara package.
pip install yara

What I don't understand is when I install yara, after upgrading distribute, why does the yara setup also download and build the distribute 0.6.25 egg?

If distribute >= 0.6.25 is a hard requirement to install the yara package, why can't the yara installer just use the version of distribute that I already have?

If for some reason the yara installer cannot use the distribute version that I already have, even if it is newer than 0.6.25, why is there a requirement for my system to have that newer version of distribute prior to installing the yara package? Especially if yara is going to download its own distribute version anyway.

I'm referring to what I see in the output here during a successful yara installation:

```
Downloading/unpacking yara (from -r requirements.txt (line 10))
  Downloading yara-1.7.5.tar.gz (392Kb): 392Kb downloaded
  Running setup.py egg_info for package yara
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.25.tar.gz
    Extracting in /tmp/tmpgS34Y_
    Now working in /tmp/tmpgS34Y_/distribute-0.6.25
    Building a Distribute egg in /home/nick/msvirtualenv/build/yara
    /home/nick/msvirtualenv/build/yara/distribute-0.6.25-py2.7.egg
```

As a separate, but related question, why does it require distribute of a specific version? With the recent re-integration of distribute and setuptools, can it also use setuptools?

Thanks,
Nick

**Comment by mjdorma** [comment]
I removed the dependency on distribute...  I recall putting in in here when I started the project to make it work on Py3x, which is no longer necessary. 

The package has been updated to 1.7.6 which should now just require setuptools. (https://pypi.python.org/pypi/yara/1.7.6)

Thanks for the bug reports.

Cheers,
Mick

**Comment by mrtizmo** [comment]
Excellent. Thank you! That simplifies my life.
